name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      
      - run: npm install
      - run: npm run build
      - run: echo "Build completed successfully"
      
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4





